// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCke0CTgLtnCTiG9EW3RzQAfqUuX680Fa8',
    appId: '1:858096950104:web:8cf7a34d20bc587693632d',
    messagingSenderId: '858096950104',
    projectId: 'bus-system-6a7ba',
    authDomain: 'bus-system-6a7ba.firebaseapp.com',
    storageBucket: 'bus-system-6a7ba.firebasestorage.app',
    measurementId: 'G-GJLZ6D1CP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwwHQEZRtAJzNqXgA7fY0gbFFas1R147A',
    appId: '1:858096950104:android:3f93cae5448b7b0c93632d',
    messagingSenderId: '858096950104',
    projectId: 'bus-system-6a7ba',
    storageBucket: 'bus-system-6a7ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWOejT1ggAAidb7POa7bgo_N4GxK6A1Qo',
    appId: '1:858096950104:ios:e8051c0332b5b42793632d',
    messagingSenderId: '858096950104',
    projectId: 'bus-system-6a7ba',
    storageBucket: 'bus-system-6a7ba.firebasestorage.app',
    iosBundleId: 'com.example.busSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWOejT1ggAAidb7POa7bgo_N4GxK6A1Qo',
    appId: '1:858096950104:ios:e8051c0332b5b42793632d',
    messagingSenderId: '858096950104',
    projectId: 'bus-system-6a7ba',
    storageBucket: 'bus-system-6a7ba.firebasestorage.app',
    iosBundleId: 'com.example.busSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCke0CTgLtnCTiG9EW3RzQAfqUuX680Fa8',
    appId: '1:858096950104:web:046f7841c90c4bf493632d',
    messagingSenderId: '858096950104',
    projectId: 'bus-system-6a7ba',
    authDomain: 'bus-system-6a7ba.firebaseapp.com',
    storageBucket: 'bus-system-6a7ba.firebasestorage.app',
    measurementId: 'G-7BCVRB4ZY5',
  );
}
